# Generated by Django 5.0.6 on 2024-05-30 18:20

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(validators=[accounts.validators.validate_birth_date])),
                ('info', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
